### ISSUE TITLE
201705_in-app : android 수정 필요

### ISSUE THREAD

**Issue by Park-Yeonsun** [iplateia/apps#2]
- [x] 데이터 수정에 대한 다운로드 적용 제대로 안됨

- [x] 앱 데이터 업데이트가 필요할 시,  간헐적으로 앱이 죽는 경우 발생

- [x] 앱 데이터 다운로드 이후 off된 커머셜에 해당되는 프로모션을 노출

- [x] 앱을 강제 중지 후, 최종 인식되었던 프로모션을 다시 인식시키는 경우, 
       동일한 프로모션에 대한 카드가 연이어 나타남

- [ ] 녹음 앱 사용시, 녹음 시작 후 완료(저장)되지 않으면 인식 안됨

자세한 내용은 아래의 링크를 참조해 주세요.
https://docs.google.com/spreadsheets/d/11mmr1UlVdM-eZ_u5n8JiYZBHAncK50ffJeCA4lETLJA/edit#gid=0

**Comment by khris** [comment]
@Park-Yeonsun 4번은 인식 기록을 저장하면서 해결했던것으로 기억하고 5번은 원래 그래서 어쩔수 없었던 문제로 기억합니다. 코멘트 보시면 이슈 닫기 여부 확인해주세요.

**Comment by Park-Yeonsun** [comment]
수정 확인했습니다. 이슈 close 합니다
