### ISSUE TITLE
201705_in-app : android 와 ios의 차이 정리

### ISSUE THREAD

**Issue by Park-Yeonsun** [iplateia/apps#3]
1. 수정된 데이터를 불러오는 기준 : 화면 바뀜
   : 단, android의 경우 알림센터는 화면이 바뀌었다고 인지 되지 않아, 수정된 데이터를 받아오지 못함.

2. 이미지 노출
   - ios : 등록된 이미지 비율에 맞추어 모두 노출 (리스트, 상세 모두)
   - android : 등록된 이미지를 3:2 비율로 자동 크롭 하여 노출 

3. 기타
   - ios 앱 속성에 따른 차이 : 서버인식 & 인앱 버전
       - 서버 인식의 경우, 녹음기, 샤잠 사용에 상관없이 인식 가능
            > 녹음 중인 상태로 인식 시도 해도 인식 (녹음은 녹음대로 진행)
            > 샤잠을 사용해도 인식 가능
  

자세한 내용은 아래의 링크를 참조해 주세요.
https://docs.google.com/spreadsheets/d/11mmr1UlVdM-eZ_u5n8JiYZBHAncK50ffJeCA4lETLJA/edit#gid=0

**Comment by khris** [comment]
@Park-Yeonsun 이야기가 따로 되었던것으로 기억하는데 이슈 한 번 확인부탁드립니다.

**Comment by Park-Yeonsun** [comment]
1. os적인 부분.
2. ios도 이미지 고정형으로 수정됨
3. ios도 인앱버전, 백그라운드 버전 개발로 android와 별 차이 없음.

이슈 닫습니다. 2018.03.12
